[mypy]
python_version = 3.12
ignore_missing_imports = True
plugins = sqlalchemy.ext.mypy.plugin

# Точечные игноры для сложных случаев
[[mypy.overrides]]
module = ["src.db.database"]
disable_error_code = ["call-overload", "assignment"]

[[mypy.overrides]]
module = ["src.worker.tasks"]
disable_error_code = ["union-attr"]

[[mypy.overrides]]
module = ["src.auth.router", "src.auth.service", "src.billing.router"]
disable_error_code = ["union-attr", "arg-type", "return-value"]
