[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests

filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:jose.*
    ignore::DeprecationWarning:.*on_event.*
    ignore::DeprecationWarning:fastapi.*
    ignore::DeprecationWarning:starlette.*
